<?php

return [
    'tui' => [
        [
            'slug' => 'shellframe',
            'name' => 'shellframe',
            'tagline' => 'TUI framework for bash',
            'description' => null,
            'install' => 'brew install fissible/tap/shellframe',
            'install_label' => 'brew',
            'install_note' => null,
            'docs_url' => 'https://docs.fissible.dev/shellframe',
            'github_url' => 'https://github.com/fissible/shellframe',
            'suite' => 'tui',
            'features' => [
                'Full widget set: list, grid, editor, tree, modal, tab-bar, input-field, app shell',
                'Composable shellframe_shell runtime with dirty-region rendering',
                '1000+ tests across bash 3.2–5.x',
                'Split-pane layout, diff-view, and synchronized scrolling',
            ],
            'code_example' => "source shellframe.sh\n\nshellframe_list_init items\nshellframe_list_add items \"Option A\"\nshellframe_list_add items \"Option B\"\nshellframe_shell run",
            'screenshots_label' => null,
            'screenshots' => [],
            'marketing_sections' => [],
        ],
        [
            'slug' => 'seed',
            'name' => 'seed',
            'tagline' => 'Bash fake data generator',
            'description' => null,
            'install' => 'brew install fissible/tap/seed',
            'install_label' => 'brew',
            'install_note' => null,
            'docs_url' => 'https://docs.fissible.dev/seed',
            'github_url' => 'https://github.com/fissible/seed',
            'suite' => 'tui',
            'features' => [
                '31 generators across scalar, record, ecommerce, CRM, and TUI categories',
                '4 output formats: JSON, CSV, SQL, key-value',
                'No runtime, no package manager — bash and awk only',
                'MCP server for AI-assisted test data generation',
            ],
            'code_example' => "# Generate 10 user records as JSON\nseed record.user --count 10 --format json\n\n# Generate a CSV of 100 products\nseed ecommerce.product --count 100 --format csv",
            'screenshots_label' => null,
            'screenshots' => [],
            'marketing_sections' => [],
        ],
        [
            'slug' => 'ptyunit',
            'name' => 'ptyunit',
            'tagline' => 'PTY test framework for bash',
            'description' => 'Test your bash scripts — even the interactive ones that take over the terminal. ptyunit is the only bash test framework with real pseudoterminal support, built-in mocking, native code coverage, and zero dependencies.',
            'install' => 'brew install fissible/tap/ptyunit',
            'install_label' => 'brew',
            'install_note' => null,
            'docs_url' => 'https://docs.fissible.dev/ptyunit',
            'github_url' => 'https://github.com/fissible/ptyunit',
            'suite' => 'tui',
            'features' => [
                '221 assertions for terminal and PTY output testing',
                '15× faster than bats-core for PTY-dependent test suites',
                'Used by shellframe, shellql, and seed',
                'Bash 3.2–5.x compatible',
            ],
            'code_example' => "source ptyunit.sh\n\npty_test \"shows welcome screen\" <<'EOF'\n  pty_run \"shql\"\n  pty_assert_contains \"Welcome to shellql\"\nEOF",
            'screenshots_label' => null,
            'screenshots' => [],
            'marketing_sections' => [
                [
                    'title' => 'Most test frameworks stop at stdout',
                    'body' => 'If your script opens /dev/tty for a menu, a prompt, or a TUI — standard test tools can\'t touch it. ptyunit runs your script inside a real pseudoterminal, sends keystrokes like a human, strips ANSI escape codes, and gives you clean text to assert against. Menus, password prompts, progress bars, fzf pickers, dialog boxes — all testable.',
                    'code' => "# Drive a TUI with keystrokes, assert on the result\nout=\$(python3 pty_run.py my_menu.sh DOWN DOWN ENTER)\nassert_contains \"\$out\" \"You selected: cherry\"",
                ],
                [
                    'title' => 'Real bugs in real code',
                    'body' => 'We pointed ptyunit at a 1,000-line bash TUI password generator posted on Reddit — no tests, two operating modes, keyboard navigation, history tracking, and i18n. ptyunit found a silent flag-ordering bug where -d (DB-safe) and -s (simple) conflict depending on order — passwords were labeled "DB-safe" but contained no DB-safe characters. It caught a crash when -l is passed without a value, and a bash 4.3 compatibility issue in the history code that only manifests interactively. None of the TUI behavior — mode toggles, history navigation, the help screen, language switching via arrow keys — is reachable from any other test framework.',
                    'code' => "test_that \"DB-safe flag wins regardless of flag order\"\nrun passgen -d -s -l 24 -q\nassert_match '[_.\\-]' \"\$output\"\n\ntest_that \"history navigation shows correct position\"\nout=\$(python3 pty_run.py passgen r r r '<' q)\nassert_contains \"\$out\" \"2/3\"",
                ],
                [
                    'title' => 'Mocking with zero boilerplate',
                    'body' => 'Replace any command with a fake. Record every call. Verify arguments and call count. Mocks clean up automatically at the next test boundary — no manual teardown. Need smarter behavior? Use a heredoc body to write conditional logic.',
                    'code' => "test_that \"deploy pushes to staging\"\nptyunit_mock git --output \"pushed\"\nptyunit_mock curl --exit 0\n\ndeploy_to_staging\n\nassert_called git\nassert_called_with git \"push\" \"origin\" \"staging\"\nassert_called_times curl 1",
                ],
                [
                    'title' => 'Coverage that works everywhere',
                    'body' => 'Built-in code coverage via PS4 tracing — no kcov, no Linux-only tools. Works on macOS. PTY integration tests contribute to coverage automatically: TUI code paths exercised through the PTY driver appear in the report with no extra configuration. Set a minimum threshold to gate CI.',
                    'code' => null,
                ],
            ],
        ],
        [
            'slug' => 'shellql',
            'name' => 'shellql',
            'tagline' => 'SQLite workbench that runs where your data lives',
            'description' => "You SSH into a server. The SQLite database is right there. Every GUI tool you own stops working.\n\nShellQL is a full SQLite workbench that runs in your terminal. Open a database on any server you can SSH into. Browse schemas, run queries, and edit records without leaving the shell. Runs on bash 3.2–5.2 across macOS and Linux, tested in CI.",
            'install' => 'brew install fissible/tap/shellql',
            'install_label' => 'brew',
            'install_note' => 'Works over SSH. No GUI. No port forwarding.',
            'docs_url' => 'https://docs.fissible.dev/shellql',
            'github_url' => 'https://github.com/fissible/shellql',
            'suite' => 'tui',
            'features' => [
                'Schema browser, table view, query tab, and record inspector',
                'Full CRUD — insert, update, and delete rows with an intuitive UI',
                'Works over SSH — browse and edit data directly on the machine',
                'Mouse and keyboard support; bash 3.2–5.2, tested in CI across macOS and Linux',
            ],
            'code_example' => "# Open a database directly\nshql myapp.db\n\n# Use a named connection from sigil\nshql --connection production",
            'screenshots_label' => 'Schema browser · Table view · Record editor',
            'screenshots' => [
                '/screenshots/shellql/schema-browser.png',
                '/screenshots/shellql/table-data-view.png',
                '/screenshots/shellql/row-editor.png',
            ],
            'marketing_sections' => [
                [
                    'title' => 'Works where your data lives',
                    'body' => 'Remote servers. Docker containers. CI jobs. If the machine has bash and sqlite3, you can open the database directly. No GUI install. No port forwarding. No syncing files back to your laptop. SSH in and run it.',
                    'code' => "# Local\nshql myapp.db\n\n# Remote — SSH and run directly\nssh user@server\nshql /var/app/production.db\n\n# Named connection from sigil\nshql --connection production",
                ],
                [
                    'title' => 'Browse, query, and mutate',
                    'body' => 'ShellQL has four screens: a schema browser for listing all tables and views, a table view with inline filtering and multi-tab support (open several tables at once), a query tab for raw SQL execution, and a record editor — a schema-aware form overlay that shows column types and constraints. Insert, update, and delete are first-class. Table creation uses a SQL tab preloaded with a CREATE TABLE template, giving you full DDL control.',
                    'code' => null,
                ],
                [
                    'title' => 'Keyboard-driven, mouse-friendly',
                    'body' => 'Most terminal tools pick one input model. ShellQL supports both. Navigate screens and records with keyboard shortcuts for speed, or use the mouse when that\'s faster. Keybindings are shown at the bottom of each screen — you don\'t need to read the docs to get started.',
                    'code' => null,
                ],
                [
                    'title' => 'Zero dependencies, real architecture',
                    'body' => 'No runtime dependencies beyond bash and sqlite3 — both available on most systems. Built on shellframe, a TUI framework for bash that provides screen management, keyboard routing, and component lifecycle. Tested on bash 3.2–5.2 across macOS and Linux in CI.',
                    'code' => 'brew install fissible/tap/shellql',
                ],
            ],
        ],
    ],

    'php' => [
        [
            'slug' => 'accord',
            'name' => 'accord',
            'tagline' => 'OpenAPI contract validator for Laravel',
            'description' => null,
            'install' => 'composer require fissible/accord',
            'install_label' => 'composer',
            'install_note' => null,
            'docs_url' => 'https://docs.fissible.dev/accord',
            'github_url' => 'https://github.com/fissible/accord',
            'suite' => 'php',
            'features' => [
                'Runtime middleware validates requests and responses against your OpenAPI spec',
                'PSR-7/15 + Laravel driver — works with any PSR-15 stack',
                'OpenAPI 3.0 support',
                'Zero configuration for standard Laravel routes',
            ],
            'code_example' => "// config/accord.php\nreturn [\n    'spec'               => base_path('openapi.yaml'),\n    'validate_requests'  => true,\n    'validate_responses' => true,\n];",
            'screenshots_label' => null,
            'screenshots' => [],
            'marketing_sections' => [],
        ],
        [
            'slug' => 'drift',
            'name' => 'drift',
            'tagline' => 'API drift detection and changelog generation',
            'description' => null,
            'install' => 'composer require fissible/drift',
            'install_label' => 'composer',
            'install_note' => null,
            'docs_url' => 'https://docs.fissible.dev/drift',
            'github_url' => 'https://github.com/fissible/drift',
            'suite' => 'php',
            'features' => [
                'Detects breaking and non-breaking changes between OpenAPI specs',
                'Semver impact analysis: major, minor, or patch bump',
                'Changelog generation from spec diffs',
                'Artisan commands: accord:version, drift:changelog',
            ],
            'code_example' => "# Detect changes and suggest version bump\nphp artisan accord:version\n\n# Generate changelog from spec diff\nphp artisan drift:changelog",
            'screenshots_label' => null,
            'screenshots' => [],
            'marketing_sections' => [],
        ],
        [
            'slug' => 'forge',
            'name' => 'forge',
            'tagline' => 'OpenAPI spec scaffolding from Laravel routes',
            'description' => null,
            'install' => 'composer require fissible/forge',
            'install_label' => 'composer',
            'install_note' => null,
            'docs_url' => 'https://docs.fissible.dev/forge',
            'github_url' => 'https://github.com/fissible/forge',
            'suite' => 'php',
            'features' => [
                'Generates OpenAPI 3.0 specs from your existing Laravel routes',
                'Reads FormRequest validation rules to populate request schemas',
                'Artisan command: accord:generate',
                'Augments an existing spec or generates from scratch',
            ],
            'code_example' => "# Generate openapi.yaml from your routes\nphp artisan forge:generate --output openapi.yaml",
            'screenshots_label' => null,
            'screenshots' => [],
            'marketing_sections' => [],
        ],
    ],

    'paid' => [
        [
            'slug' => 'guit',
            'name' => 'guit',
            'tagline' => 'A terminal git client',
            'description' => 'A keyboard-driven terminal git client built on shellframe. Working copy, history, cherry-pick, branch graph, and a 3-pane merge resolver that registers as git mergetool.',
            'status' => 'coming-soon',
            'formspree_id' => 'xzdkzjyn',
            'docs_url' => null,
            'features' => [],
            'marketing_sections' => [],
            'screenshots' => [],
            'screenshots_label' => null,
            'pricing_note' => null,
        ],
        [
            'slug' => 'sigil',
            'name' => 'sigil',
            'tagline' => 'Developer credential and connection broker',
            'description' => 'A local-first CLI that stores secrets, database connections, SSH profiles, and API tokens — with a pipeline-composable interface and OS keychain backend. Built in Rust.',
            'status' => 'purchase-pending',
            'formspree_id' => 'xeepornj',
            'docs_url' => null,
            'features' => [],
            'marketing_sections' => [],
            'screenshots' => [],
            'screenshots_label' => null,
            'pricing_note' => null,
        ],
        [
            'slug' => 'station',
            'name' => 'Station',
            'tagline' => 'The Laravel CMS for agencies managing multiple client sites.',
            'description' => 'Self-hosted on your infrastructure. Multi-tenant client sites. Approval-first publishing. Built for agencies that do not want another CMS stack per account.',
            'status' => 'coming-soon',
            'formspree_id' => 'mojpvkrq',
            'docs_url' => 'https://docs.fissible.dev/station/',
            'pricing_note' => 'One self-hosted install for many client sites. No SaaS lock-in.',
            'screenshots_label' => 'Approval queue · Content editor · Site switcher',
            'screenshots' => [],
            'features' => [
                ['title' => 'Client approval is enforced, not implied', 'body' => 'Draft -> Submit -> Approve -> Publish is the default path. Client sign-off becomes workflow state, not an email thread someone has to remember.'],
                ['title' => 'One install for many client sites', 'body' => 'Run multiple client sites from one Station install while keeping content, users, menus, and approval boundaries isolated per tenant.'],
                ['title' => 'Scheduling that respects review', 'body' => 'Future publishing happens after approval, not instead of approval. Station keeps campaign timing and client sign-off aligned.'],
                ['title' => 'Version history for awkward conversations', 'body' => 'Keep a clear record of what changed, who changed it, and when it was approved so your team can answer client questions without archaeology.'],
                ['title' => 'Self-hosted on infrastructure you control', 'body' => 'Deploy Station on your own server, keep client data under your operational control, and avoid making every client site another SaaS dependency.'],
                ['title' => 'Built on Laravel conventions your team can inspect', 'body' => 'Filament admin patterns, Laravel internals, and an ecosystem of public tools make the stack understandable for technical agency teams.'],
            ],
            'marketing_sections' => [
                [
                    'title' => 'Every new client should not mean another CMS stack',
                    'body' => 'Agencies with five, ten, or twenty client sites usually inherit the same mess: separate installs, separate subscriptions, inconsistent approval rules, and a growing list of places where content can go live too early. Station is designed around one self-hosted install with isolated client tenants.',
                ],
                [
                    'title' => 'Who Station is for',
                    'body' => 'Small agencies managing roughly 5-20 client sites, especially when clients need to approve content before it publishes. It also fits regulated client work, franchise groups, and multi-site organizations, but the core buyer is the agency that wants fewer CMS installs and fewer approval workarounds.',
                ],
                [
                    'title' => 'What the first release focuses on',
                    'body' => 'Approval-first content workflows, tenant-aware site isolation, client-safe review paths, version history, scheduled publishing after approval, auditability, and a Laravel + Filament admin that feels familiar to technical agency teams.',
                ],
                [
                    'title' => 'Self-hosted economics for agency retainers',
                    'body' => 'Station is sold as software, not as a hosted service. You run it on your infrastructure, keep client data under your control, and avoid turning every new client site into another recurring CMS bill. Multi-tenancy is what makes that model work without mixing clients together.',
                ],
            ],
        ],
        [
            'slug' => 'conduit',
            'name' => 'conduit',
            'tagline' => 'A terminal HTTP client',
            'description' => 'Request builder, collections, response viewer, and sigil credential integration in the free tier. Paid tier adds accord/drift contract validation in-terminal.',
            'status' => 'coming-soon',
            'formspree_id' => 'xpqowybq',
            'docs_url' => null,
            'features' => [],
            'marketing_sections' => [],
            'screenshots' => [],
            'screenshots_label' => null,
            'pricing_note' => null,
        ],
    ],
];
